  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
  labels:
    run: ums
spec:
  selector:
    matchLabels:
      run: ums
  replicas: 1
  template:
    metadata:
      labels:
        run: ums
    spec:
      containers:
      - name: ums
        image: robydocker/ums:1.0
        ports:
        - containerPort: 80

---

apiVersion: v1 
kind: Service
metadata:
  name: ums-service
  labels:
    run: ums
spec:
  selector:
    run: ums
  type: NodePort
  ports:
  - nodePort: 30001
    port: 91
    targetPort: 80
